version: '3.2'
services:
  db:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_USER: crudapp
        MYSQL_PASSWORD: passwd
        MYSQL_DATABASE: crudapp
